src/actions/query.js

`once` cannot be passed to `on`, it is a function unto itself.
the `populates` filter was truthy even when the params were queries because `indexOf` returns an index or `-1` if not present.

fix once (#2) and queries (#3)

---

src/utils/auth.js

The providerName should be used in the creation of the provider instead of the provider itself

Updated param name in createAuthProvider()

---

src/helpers.js
src/utils/auth.js
test/setup.js
test/unit/actions/auth.spec.js
test/unit/actions/query.spec.js
test/unit/compose.spec.js
test/unit/connect.spec.js
test/unit/helpers.spec.js
test/unit/reducer.spec.js

* Tests added for reducer
* Helpers tests improved

Reducer and Helper Tests

---

package.json
src/compose.js
test/unit/compose.spec.js

* `ref` is now a function in compose (Addresses #28)
* test added to confirm that `ref` is exposed correctly
* Peer Dependencies updated to include `react-redux` `^5.0.0` and ` redux` `^3.6.0`

Version v1.1.5

---

package.json
src/actions/auth.js
src/helpers.js
src/reducer.js
src/utils/populate.js
test/unit/helpers.spec.js
test/unit/reducer.spec.js

* Single item with iterable child population now supported with `populatedDataToJS`
* `getRedirectResult` no longer calls dispatches `LOGOUT` on null response (fixes refresh issue with redux-auth-wrapper).
* `isLoading` typo corrected to `isInitalizing` in logout reducer case

Version v1.2.1

---

.eslintignore
examples/snippets/decorators/App.js
examples/snippets/populates/App.js
package.json
src/helpers.js
src/utils/populate.js
test/unit/helpers.spec.js
test/unit/utils/populate.spec.js

* Population of list with items containing a child param that is Firebase list (`key: true`) using `populatedDataToJS` (#42)
* `populatedDataToJS` supports childParam option (#48)
* `populatedDataToJS` returns null for empty lists instead of `undefined` (#50)
* Unit tests added to cover all cases within `populatedDataToJS`

Version v1.2.3

---

docs/queries.md

Query.limitToFirst: First argument must be a positive integer.

Fix limitToFirst example

---

.travis.yml
docs/auth.md
package.json
src/actions/auth.js
src/compose.js
tests/unit/actions/auth.spec.js

* `confirmPasswordReset` action added from #74 (thanks @rpeterson)
* `verifyPasswordResetCode` action added
* If no profile is passed to `firebase.createUser`, email is used by default
* Docs updated with new methods
* Tests added for new auth actions

Version v1.3.2

---

.travis.yml
package.json
src/actions/query.js
webpack.config.js

* `react-redux` and `redux` removed from peer dependencies
* `react-redux` and `redux` removed from bundle externals
* dependencies in travis `before_install` removed (unnecessary)

Version v1.3.3

---

docs/storage.md

I deleted the line `const {newTodo} = this.refs` of the file string upload example because it seemed unnecessary to me.

docs(example): remove refs from storage example

---

package.json
tests/unit/helpers.spec.js
tests/unit/utils/actions.spec.js
tests/unit/utils/query.spec.js

* #92, #94 - Issue with query params containing numbers (thanks @biomorgoth)
* #82, #83 - dispatch parameter fixed in `unWatchEvent`
* #89 - Separate sections added to docs for [`props.firebase`](http://react-redux-firebase.com/docs/api/props-firebase.html) and [`getFirebase`](http://react-redux-firebase.com/docs/api/get-firebase.html)

Version v1.3.4

---

.npmignore
package.json
src/compose.js
tests/unit/compose.spec.js

* fix using with yarn - `.npmignore` file removed so that `.yarn.lock` file will not be included in npm release (only files listed in package file `files` property)
* `pushWithMeta`, `setWithMeta`, and `updateWithMeta` methods added - write to firebase with createdAt/updatedAt and createdBy/updatedBy

Version v1.4.0 Beta 2

---

package.json
src/actions/auth.js
src/utils/populate.js

Non-breaking small feature addition to profile parameter population.  Profile population will now work on a list of UIDs, key:value pairs, and a single UID (which was already supported).

Population of profile params

---

package.json

Removed `browser` field from `package.json` in attempt to solve #128 
* [#128](https://github.com/prescottprue/react-redux-firebase/issues/#128)

Version v1.5.0 alpha.2

---

src/constants.js

Webpack 2 doesn't allow to mix import/export with module.exports.
This forbids to use src in webpack, which is required for dead code elimination (tree shaking) to work.
- Will a new version need to be released or is this a docs change? **YES**
- Which version should this be published as a part of? **ASAP**
- Does this impact the external API? **NO**
- Will it need to be a breaking change? **NO**

Don't mix import/export with module.exports

---

src/actions/query.js
tests/unit/actions/query.spec.js

`unWatchEvent` was not passing the correct `queryId` or `path` param (i.e. matching params passed to `watchEvent`), causing internal `firebase._.watchers` to continuously grow due to `unsetWatcher` being unable to resolve the watcher. This manifests as open firebase subscriptions continuing to grow, even when then the component that issued the query that opened the subscription is unmounted.
PR fixes the passed params so that `unsetWatcher` is able to clean up the watchers on unmount. Best test case for this is probably to compare that `firebase._.watchers` map after component mount and component unmount, and compare this PR against behavior on master.
- Will a new version need to be released or is this a docs change?
New version.
- Which version should this be published as a part of? …

fix: unwatch events with same parameters as original watch

---

src/connect.js

It allow to use more than one firebase app by using separate store for each one and connect components to different stores.
- Will a new version need to be released or is this a docs change? **YES**
- Which version should this be published as a part of? **ASAP**
- Does this impact the external API? **YES**
- Will it need to be a breaking change? **NO**
- [-] All tests passing
- [-] Docs updated with any changes or examples
- [-] Added tests to ensure feature(s) work properly
* [#29](https://github.com/prescottprue/react-redux-firebase/issues/29)

Allow to use different stores in firebaseConnect

---

examples/complete/material/src/routes/Projects/containers/ProjectsContainer.js

Fixes an issue in the material example where the delete button would never display.

fix(examples/complete/material-ui): project showDelete always false

---

src/compose.js
src/createFirebaseInstance.js
tests/unit/compose.spec.js

Make `getFirebase` properly exposed as it is in 1.x
Added functions:  `updateAuth`, `updateEmail`, and `updateProfile` to `firebaseInstance`.
`getFirebase` is undefined. I can't use `thunk` anymore.

[v2.0.0] fix(getFirebase): expose getFirebase

---

src/compose.js

Check that 'database' is a function instead of 'initializeApp'. This allows for passing in of pre-initialized firebase instances (like react-native-firebase).
When using react-native-firebase:
```
import firebase from 'react-native-firebase'
import { reactReduxFirebase } from 'react-redux-firebase'
const FBConfig = {
debug: false,
persistence: true
}
const reactReduxFBConfig = {
enableLogging: false,
userProfile: 'users',
}
const firebaseApp = firebase.initializeApp(FBConfig)
compose(
reactReduxFirebase(firebaseApp, reactReduxFBConfig)
...
)
```
Returns the error: **databaseURL is a required config parameter for react-redux-firebase**
In this case, react-redux-firebase tries to parse firebaseApp as a config object, because it no longer contains the initalizeApp function. This PR addresses …

[v2.0.0] fix(initialize): Check that 'database' is a function instead of 'initializeApp'

---

examples/complete/react-native/package.json
examples/complete/react-native/src/Home.js
examples/complete/react-native/yarn.lock
package.json
src/connect.js
src/index.js

* `createFirebaseConnect` exposed (for creating `firebaseConnect` functions that connect to different stores)
* Added back unnecessarily removed `firebaseConnect` functionality
* Fixed react-native example to use `v2.0.0` practices

Version v2.0.0 Alpha 4

---

.babelrc
.npmignore
examples/complete/react-native/package.json
examples/complete/react-native/yarn.lock
package.json

* Reverted back to `add-module-exports` to fix issue with base level exports (breaking react-native example)
* More files added to `.npmignore` including:
* .travis.yml
* CODE_OF_CONDUCT.md
* CHANGELOG.md
* .codeclimate.yml
* PATRONS.md

Version v2.0.0 Alpha 7

---

src/actions/auth.js

When a user logs in with Facebook, the userData is in the following format:
```javascript
{
email: ...
displayName: ...
providerData: [
{
email: ...
photoURL: ...
providerId: facebook.com
uid: ...
displayName: ...
...
}
]
...
}
```
there is no `user` in `userData` so it was failing creating the profile. This pr fixes that.

Fix createUserProfile on login with Facebook

---

package.json
src/connect.js

Adds two statics to a connected component:
- `WrappedComponent`, which is the original component. This is useful for testing without mocking out firebase.
- `displayName` is set to reveal what component is wrapped by FirebaseConnect. This makes debugging easier.
This will require a new version (presumably 1.4.4) but is purely additive and therefore should not break any existing code, unless people were relying on the previous behavior of `displayName`.

feat(firebaseConnect): expose wrapped component and displayName

---

package.json
src/connect.js
tests/unit/connect.spec.js
yarn.lock

* Adds two statics to a connected component:
* `wrappedComponent`, which is the original component (useful for testing without mocking firebase)
* `displayName` is set to reveal what component is wrapped by FirebaseConnect. This makes debugging easier
* Tests added for both new statics listed above
* Remove open collective as a dependency (not used in `postinstall`)
* #188

Version 1.4.4

---

docs/roadmap.md
index.d.ts
package.json
src/actions/auth.js
src/compose.js
tests/unit/connect.spec.js
tests/unit/firebaseConnect.spec.js

* Fix race condition with `uniqueSet` - #207
* Usage of `profileFactory` is wrapped in try/catch to handle and reject errors within provided factory function
* Typescript Typings updated make `notSetValue` not required (i.e. dataToJS(firebase, 'todos') instead of dataToJS(firebase, 'todos', undefined)) - #214 
* #207 
* #214

v1.5.0 Release Candidate 3

---

docs/api/compose.md
src/actions/auth.js

1. Presence can now be defined as a function `(user, firebase) -> string` to provide dynamic keys for storing the presence states.
2. Sessions can now be set to `null` to prevent the sessions variable from being created.

feat(presence): presence and sessions options accept functions

---

src/helpers.js

Small bug fix to make populate function work with deep root paths in v2.0.0.
#223

fix(populate): Deep path roots do not work with population (v2.0.0)

---

package.json
src/actions/query.js

When multiple listeners are set on the same path with different query parameters, all of the paths are not correctly unwatched when the component unmounts.
Passing queryId into the unWatchEvent function is necessary for
unique queries on the same base path to be properly identified when
unwatching events.  getQueryIdFromPath and getWatchPath do not
correctly identify unique queries at the same path (because the path
that is passed into these functions is the path without query strings
attached).  This scenario happens when using storeAs functionality.
- [X ] All tests passing (except one test that was failing prior to this PR)
- [NA] Docs updated with any changes or examples if applicable
- [NA ] Added tests to ensure new feature(s) …

Correctly unwatch multiple queries to the same base path.

---

src/reducer.js
tests/unit/reducer.spec.js

V2 appears to have dropped the firebase.authError redux state present in v1.x. This PR adds it back to maintain better backwards compatibility.

[v2.0.0] feat(reducers): authError reducer to mirror authError state in v1

---

src/reducer.js

This is an update to PR 224, which did not go far enough at deeply merging data into the redux state.
Note: lodash's merge function appears to do a deep clone of the merged objects, which is likely unnecessary and expensive here. It would be nice to avoid this but there is no obvious way to accomplish this with lodash so I'm leaving it for a later PR.
#223

fix(populate): Update to deep path roots do not work with population (v2.0.0)

---

docs/populate.md

The snippet is replacing the email, not the displayName.

docs(example): fix typo - the snippet is replacing the email, not the displayName

---

src/utils/auth.js

At the moment, I am trying to [authenticate using a phone number](https://firebase.google.com/docs/auth/web/phone-auth) and using `const credential = firebase.auth.PhoneAuthProvider.credential(confirmationResult.verificationId, code);` as a method of retrieving a credential to authenticate. However, this method of authentication can not be achieved currently, because `phone` is not in the list of supported providers. Instead of adding `phone` to the list of supported providers, why don't we just make `signInWithCredential` not dependant on whether a provider name is provided. Because `signInWithCredential` doesn't require provider :)

feat(auth): make signInWithCredential not dependent on provider

---

src/reducer.js
tests/unit/reducer.spec.js

Fixes #228, tests added
`_.set` does not respect numeric object keys.  Use `_.setWith` instead:
```js
const path = getDotStrPath('/analyses/123')  // => 'analyses.123'
_.set(path, { data: true }, {})              // => { analyses: [ undefined x 123 ] }
_.setWith(Object, path, { data: true }, {})  // => { analyses: { 123: { data: true } } }
```
There are many [lodash issues](https://github.com/lodash/lodash/issues?utf8=%E2%9C%93&q=is%3Aissue%20set%20number%20is%3Aclosed%20) and [SO posts](https://www.google.com/search?safe=active&biw=1439&bih=799&q=site%3Astackoverflow.com+lodash+set+number&oq=site%3Astackoverflow.com+lodash+set+number&gs_l=psy-ab.3...2213.2450.0.2572.4.4.0.0.0.0.0.0..0.0....0...1.1.64.psy-ab..4.0.0.ZlLLR7chKyY) about this bizarre design decision but it looks like it is …

fix(reducer): allow setting paths ending in numbers

---

README.md
docs/api/compose.md
docs/recipes/populate.md
docs/recipes/ssr.md
docs/roadmap.md
examples/complete/material/config/webpack.config.js
examples/complete/material/src/store/createStore.js
package.json
src/actions/auth.js
src/actions/query.js
src/actions/storage.js
src/compose.js
src/constants.js
src/createFirebaseInstance.js
src/reducer.js
src/utils/auth.js
src/utils/index.js
src/utils/storage.js
tests/unit/reducer.spec.js

* fix(reducer): allow setting paths ending in numbers - #248
* feat(auth): make signInWithCredential not dependent on provider - #247
* `signInWithCustomToken` no longer decodes token internally for profile data (`profileFactory` should be used) - #244
* Removed `jwt-decode` as a dependency (not needed since auth token no longer decoded internally)
* Support lazy/module loading - #249, #250 
* Updated SSR docs to include notes about `enableRedirectHanlding: false` - #251
* Updated Roadmap with detection of non-http environments
* #244
* #245
* #247
* #248
* #249
* #250
* #251

v2.0.0 beta.7

---

src/actions/query.js
src/constants.js
src/reducer.js
tests/unit/reducer.spec.js

I previously made the v2.0.0 SET action merge redux state data rather than overwrite it. This fixed a bug with multiple queries using population (and likely also issue #130), but it had unintended consequences for regular data subscriptions (most notably: if a field is deleted from a single object being subscribed to, it won't get deleted by the reducer).
This PR reverts that change and introduces a new MERGE action that keeps this merge semantics when useful. For now, I use MERGE when populating data only to fix the aforementioned bug. Down the road, it can be exposed to end-users as an option in a query. This may be useful, for example, when subscribing to collections of objects that one might not want to overwrite across different containers.
If not relevant to pull request, check off …

fix(reducer):  MERGE action added and SET action to reverted to v1 behavior

---

.babelrc
src/helpers.js
tests/unit/helpers.spec.js

Fixed populate function to return null for null paths.
Also made a small change to babelrc file to make tests run in my environment.

fix(populate) Fixed populate function to return null for null paths.

---

docs/recipes/redux-saga.md

Correct title in redux saga docs from "Redux Form Recipes" -> "Redux Saga Recipes"
* #276

fix(docs): typo in redux-saga recipe doc

---

docs/recipes/routing.md

The `authenticatedSelector` for `UserIsNotAuthenticated` was wrong. Currently both conditions are the same, which leads to an infinite redirect.

Fix error in redux-auth-wrapper example

---

docs/api/constants.md
docs/api/firebaseInstance.md
docs/storage.md
package.json
src/actions/auth.js
src/actions/query.js
src/actions/storage.js
src/constants.js
src/createFirebaseInstance.js
src/reducer.js
tests/unit/actions/auth.spec.js
tests/unit/actions/query.spec.js
tests/unit/enhancer.spec.js
tests/unit/reducer.spec.js

* bugfix(auth): `auth.isLoaded` set to `true` on `AUTH_EMPTY_CHANGE` action dispatch - #290
* feat(storage): customizable file name with `uploadFile` and `uploadFiles` through `name` option (can be String or Function) - #285
* bugfix(query): `remove` dispatches `REMOVE` action type with associated reducer case - #257
* feat(query): `remove` accepts an options object as third argument
* feat(query): `remove` now has `dispatchAction` option for disabling dispatch of new `REMOVE` action type
* feat(query): `dispatchRemoveAction` config option add for global control of dispatching when calling `remove`
* #257
* #285
* #290

v2.0.0-beta.10

---

src/helpers.js
tests/unit/helpers.spec.js

This is a minor update to `populateChild` function in `helpers.js` to returns `null` instead of `child`. This works because the returned value is used in `reduce` function that combines values. 
Previously, already written populates values could be overwritten when `child` was returned.
A new failing test was written to reproduce the issue and is now passing. I've also confirmed this fix in a private repo with `npm link`.
Fixes #277.

fix(populate): multiple populates when missing child key

---

src/createFirebaseInstance.js
tests/unit/enhancer.spec.js

This PR adds a new `connect` helper to the props.firebase object that lets users connect their redux store to the firebase DB without requiring the firebaseConnect HOC. This is useful for populating your redux state ahead of rendering your React app, a typical pattern when performing server side rendering.

feat(core): non-HOC version of firebaseConnect, for use with server side rendering

---

docs/api/props-firebase.md
docs/integrations/react-native.md
index.d.ts

This is a fix to this error we currently get when using typescript on the beta.12 branch:
```Build failed!
✖ ERROR [at-loader] ./node_modules/react-redux-firebase/index.d.ts:137:1
TS1185: Merge conflict marker encountered.
```
From what i understand, this came from a merge conflict so i went ahead and patched it :)
Also, while i'm at it, thanks for the great lib ️:heart:

Remove an artifact from a previous merge conflict

---

src/helpers.js

Add getValueAt function for easy migration to v2 from dataToJS and pathToJS

---

src/actions/auth.js
src/reducer.js

Adds EMPTY_AUTH_CHANGE case to profile reducer, so that firebase.profile is also updated to `{ isLoaded: true, isEmpty: true }` on empty auth changes.

Add EMPTY_AUTH_CHANGE case to Profile Reducer

---

package.json
src/actions/auth.js

This PR adds logic to catch errors during profile parameter population.  If a the client does not have access to the data to populate, SET_PROFILE is dispatched with the unpopulated profile.  Previously, an uncaught error prevented the profile from being updated.
- [X ] All tests passing
- [N/A] Docs updated with any changes or examples if applicable
- [N/A] Added tests to ensure new feature(s) work properly

fix(populate): dispatch for errors during profile population

---

src/reducer.js

setWith sets the value to undefined, but the key remains an enumerable
property on the object.  This can cause problems when your UI iterates
over keys of an object and renders based on the key’s existence.  Using
unset, the key is removed.

Remove deep property for REMOVE action instead of setting it to undefined

---

docs/populate.md

Missing `populate` in import statement.

docs(fix): missing populate in import statement

---

src/firestoreConnect.js
tests/unit/firestoreConnect.spec.js

firestoreConnect reconnect when query params change

firestoreConnect reconnect when query params change

---

README.md

I noticed there was a duplicate section regarding Firestore in the README.

Remove extra Firestore section in README

---

docs/integrations/thunks.md

otherwise it will throw `middleware is not a function` error
for version:
```
"react-redux": "^5.0.6",
"react-redux-firebase": "^2.0.3",
"redux": "^3.7.2",
"redux-thunk": "^2.2.0"
```

fix(docs): remove typo from redux-thunk integration docs

---

docs/queries.md

`orderedToJS` is no longer available in 2.0. It was mentioned in the docs. The example was already updated though.

fix(docs): remove old reference to orderedToJS

---

docs/integrations/thunks.md

Apologies @prescottprue if these are pedantic, just fixing the docs :)
The example for thunk integrations didn't return the object correctly and would throw an error:
`Actions must be plain objects. Use custom middleware for async actions.`

Fix thunk integration example to return object correctly

---

docs/storage.md
src/actions/storage.js

Previously the typo `uploadTaskShaphot` was pervasive throughout the
variables names and return values of firebase storage upload tasks,
including in the objects returned in promise resolutions to the
end-user. This commit preserves the typos in the public interface while
also providing the correct `uploadTaskSnapshot` key in those objects.
I noticed that when handling the promise resulting from `firebase.uploadFile()` the object being returned was incorrectly providing a key named `uploadTaskSnaphot` instead of `uploadTaskSnapshot` after wondering why I kept destructuring out an undefined value.
**I could not find any existing tests related to testing this return value, so I did not add any**

fix(storage): fix a typo related to UploadTaskSnapshot within uploadFile

---

docs/storage.md

In the current example, the `Uploader` component destructures `deleteFile` directly off of `props`, but the `Uploader.propTypes` object shows that, `deleteFile` is a function on `firebase`.

Make Example Props match Proptypes

---

docs/recipes/auth.md

Fix `isLoaded(auth)` condition in the Auth Recipes docs' Google Login example code.
* #447

Fix condition in the example of Auth Recipes docs

---

docs/api/connect.md

Remove a closing parenthesis that shouldn't be there.

fix(docs): fix error in firebaseConnect example

---

docs/recipes/routing.md

Fixes the docs pointing to the wrong import location for connectedRouterRedirect in redux-auth-wrapper.
The correct import was found in the redux-auth-wrapper docs: https://mjrussell.github.io/redux-auth-wrapper/docs/Getting-Started/ReactRouter4.html

fix(docs): Bad import route for connectedRouterRedirect

---

README.md

Hey I couldn't successfully get a query to work in my project following the **Query Based On Props** section. It worked once I added `data/` to the `getVal()` path so that ``getVal(firebase, `data/todos/${props.params.todoId}\`)`` as per the example you outlined in [helpers#getVal](https://react-redux-firebase.com/docs/api/helpers.html#getval). Would this be an appropriate fix, or did I miss something?
Let me know if you'd prefer me to mock-up this issue to support the PR.

getVal missing 'data/' in path?

---

src/actions/auth.js
src/utils/auth.js
test/utils.js

As of [react-native-firebase v3.2.3](https://github.com/invertase/react-native-firebase/releases/tag/v3.2.3), `signInWithCustomToken` is deprecated in favour of `signInAndRetrieveDataWithCustomToken`.
Found a similar issue [here](https://github.com/prescottprue/react-redux-firebase/issues/467) and implemented a fallback for users in the older version of firebase as suggested.
Fixes https://github.com/prescottprue/react-redux-firebase/issues/467

feat(auth): use new firebase login methods

---

bin/api-docs-generate.js
docs/recipes/auth.md

There's a number of inconsistencies in naming of the firebaseConfig `fbConfig` and reactReduxFirebase `rrfConfig` variable names throughout the docs. These fixes just pertain to the Auth recipe. If I have time I will do a bigger site wide skim for inconsistencies.
Also when trying to open the `reactReduxFirebase` API ref I noticed the Markdown file for that page wasn't being compiled to html, the site is just serving `compose.md` when clicking on the link found here http://react-redux-firebase.com/docs/api/

fix(docs): Auth recipe fix & API Ref link fix

---

src/actions/auth.js

Auth object is being reset on successful call to updateAuth. This forces users to assume logged out state.
```auth``` should be passed instead of ```payload``` on action type AUTH_UPDATE_SUCCESS
as seen on line 192 in src/reducers.js

fix(auth): payload of AUTH_UPDATE_SUCCESS action dispatch fixed

---

docs/getting_started.md
docs/recipes/upload.md
package-lock.json
package.json
src/index.js

Fixes errors I ran into when trying to save file metadata to Firestore on upload:
- Async-related error: "ReferenceError: regeneratorRuntime is not defined" is fixed by installing babel/polyfill:  [https://github.com/babel/babel/issues/5085](https://github.com/babel/babel/issues/5085)
- Syntax for returning `downloadURL` from the fileMetadataFactory has changed; updated in docs.
Also including a small fix to the 'Getting Started' docs, which I encountered when setting up a sample project to test.
(I did not add any tests, if needed please let me know.)
#480 
#487 
#488

#487 fix(storage): fix downloadURL error in file upload metadata

---

docs/api/enhancer.md
src/enhancer.js

Fixed typo on ‘preserveOnLogout’ and '‘preserve'

fix(docs): fix typo on ‘preserveOnLogout’

---

src/utils/auth.js

signInWithCredential is deprecated in newer versions of firebase, being replaced by signInAndRetrieveDataWithCredential, which breaks federated login using credentials
Related to [this](https://github.com/prescottprue/react-redux-firebase/issues/467) issue, and already fixed for other login methods [here](https://github.com/prescottprue/react-redux-firebase/pull/484)
#467

feat(auth): Updated credential login to use new firebase method

---

index.d.ts

Fix this typescript compile error.
```
react-redux-firebase/index.d.ts(40,3):
TS2300: Duplicate identifier 'CLEAR_ERRORS'.
```
related #569

Delete duplicated identifier CLEAR_ERRORS

---

src/firebaseConnect.js

Wrongly used ReactReduxFirebaseContext.Provider instead of ReactReduxFirebaseContext.Consumer generates an error from React when firebaseConnect() is used.
While firestoreConnect() is using ReactReduxFirebaseContext.Consumer this is probably only a typo.

Fix context to Consumer instead of Provider

---

package.json
src/firebaseConnect.js

* fix(firebaseConnect): switch context to Consumer instead of Provider - @Rizzet

v3.0.0-alpha.2

---

src/actions/storage.js

When using only firestore and want to write to db to firestore. The checking is incorrect because it only consider `firebase.database` but not `firebase.firestore` when write metadata to db
https://github.com/prescottprue/react-redux-firebase/issues/600

fix(storage): support only firestore when calling upload and writing to db

---

docs/recipes/auth.md
src/createFirebaseInstance.js

To use react-firebaseui login component, the libs should expose the function `handleRedirectResult` to be used on react-firebaseui success callback
#379

exposing handle redirect result

---

src/createFirebaseInstance.js

Update `createFirebaseInstance` initialization to match `createFirestoreInstance` from `redux-firestore`. This ensures that if the instance is recreated several times, as would be the case if the provider was unmounted and remounted, it doesn't lose tracking of any existing listeners.
prescottprue/redux-firestore#174

fix(createFirebaseInstance): merge internals on instance recreation

---

docs/api/get-firebase.md

The code in `docs/api/get-firebase.md` is incorrect. This fixes it to a workable example.

docs(get-firebase): Fix getFirebase documentation example

---

docs/api/constants.md

it is not true by default
just a small docs thing, but it was annoying when what I was doing did not match what the docs indicated. No use leaving it wrong.
- [x ] All tests passing
- [x ] Docs updated with any changes or examples if applicable
- [x ] Added tests to ensure new feature(s) work properly

changed attachAuthIsReady default to false

---

index.d.ts

See #668.
I added back `<ProfileType>` in a few places so the file would be without errors; we can clean this up if we want later.
* #667

Types overhaul

---

docs/firestore.md

The following is no longer needed:
```
// Initialize Firestore with timeshot settings
firebase.firestore().settings({ timestampsInSnapshots: true })
```
@firebase/firestore: Firestore (5.9.1): 
The timestampsInSnapshots setting now defaults to true and you no
longer need to explicitly set it. In a future release, the setting
will be removed entirely and so it is recommended that you remove it
from your firestore.settings() call now.

Removed timestampsInSnapshots

---

examples/complete/material/.gitignore
examples/complete/material/README.md
examples/complete/material/firebase.json
examples/complete/material/package.json

Will change docs sections for the build script.
Will add 'start:build' script that builds the application and then serves at localhost:3000 using firebase serve.
Readme of examples/material: https://github.com/prescottprue/react-redux-firebase/tree/master/examples/complete/material#getting-started

fix(examples): updated scripts in material example to match Readme

---

docs/getting_started.md
examples/complete/firestore/README.md
examples/complete/simple/README.md

Will fix the broken links of examples and config options in the getting started section of docs.
Will fix the auth-recipes link in examples Readme.

fix(docs): update broken links in multiple sections of docs

---

.eslintrc

Will remove the warning message(Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration.) while running lint.

fix(core): add lint settings for react version to prevent warning while running lint - @Shalinit3

---

test/unit/actions/auth.spec.js
test/unit/enhancer.spec.js
test/unit/helpers.spec.js
test/unit/utils/auth.spec.js
test/unit/utils/query.spec.js

Will replace to.equal(null) with to.be.null, to.equal(undefined) with to.be.undefined and to.equal(true) with to.be.true in test cases.

fix(tests): replace instances of "to.equal" with "to.be" in tests - @Shalinit3

---

package.json
src/ReactReduxFirebaseProvider.js
src/ReduxFirestoreProvider.js

I wrapped an extended firebase instance inside react useMemo hook in order to prevent `extendedFirebaseInstance.initializeAuth()` from being called for second time when parent component updated. And it should has improved performance since it wouldn't call `createFirebaseInstance` again to create a new and change firebase instance in the `ReactReduxFirebaseContext` which would cause  update in every component that depends on firebase instance from said context.

fix(providers): prevent unwanted re-initialization when parent component updates - @illuminist

---

src/actions/auth.js

fix options not being passed to updateProfile action

fix(profile): pass updateProfile options to action

---

index.d.ts

Type definition of firebaseConnect/firestoreConnect is accepting only React.Component type which means only ClassComponent is acceptable. Changing React.Component to React.ComponentType will allow both ClassComponent and FunctionalComponent to be acceptable.
Fix https://github.com/prescottprue/react-redux-firebase/issues/736

fix(HOCs): firebaseConnect/firestoreConnect type definitions missing React.FunctionalComponent    

---

src/firebaseConnect.js

fix(firebaseConnect): move hoistStatics to allow static methods to be copied - @jeloagnasin

---

index.d.ts

This fixes a small type error on `ExtendedFirebaseInstance` from
```javascript
firestore: ExtendedFirestoreInstance
```
to
```javascript
firestore: () => ExtendedFirestoreInstance
``` 
and also fixes the return type of the `logout` function from
```javascript
logout: VoidFunction;
``` 
to
```javascript
logout: () => Promise<void>
```

fix(types): changed extended firebase instance to function

---

docs/contributing.md
package-lock.json
src/actions/auth.js

- feat(createUserProfile) Adding async to functionality to make firebase useful in profileFactory
- docs(Contributing) Adding new troubleshooting section for people struggling to NPM link react-redux-firebase (with two versions of React).
I realised that simply adding a third parameter "firebase" to profileFactory was not enough to make it useful. It's helpful to have createUserProfile awaiting the results of profileFactory. 
An example use case would be an "invited team user" without an account. On signup, it's useful to check for invited users, merge their profile data & assign with the correct roles & team.

feat(profile): add promise support for profileFactory

---

docs/recipes/routing.md

Minor change to the routing doc to change the`history`, which is unused, to `browserHistory`, which is used.

fix(docs): change unused history const to browserHistory in routing example

---

src/utils/auth.js

This fixes a bug where calling
```javascript
firebase = useFirebase()
firebase.updateProfile(..)
```
would result in a:
```
TypeError: Cannot read property '_getService' of undefined
```
insides firebase because the 'this' keyword would be undefined, caused by the destructured `database` function.

fix(profile): prevent `cannot read property '_getservice' of   undefined` error

---

index.d.ts

Linters would fail when using `rffConfig.enableClaims` [as documented](http://react-redux-firebase.com/docs/auth.html#custom-claims)
_(Nothing changed)_
_(Already documented)_
_(Not needed)_
_(Apprently, none)_

fix(types): add missing config key `enableClaims` - @lesmo

---

src/actions/auth.js

If using `userProfile` and listening path is restricted with security rules, the profile listener will stay subscribed and cause permission error when user logged out. This initially can be prevented by using `firebase.logout` which has a call to unwatch user profile, however, there is some case that firebase will force user to logout, for example, logging out via other tab. This can't be prevented by using `firebase.logout` because `auth.onAuthStateChanged` is being trigger by firebase itself.
I have tested with pure firebase sdk, and found out that unwatching user profile inside of `auth.onAuthStateChanged` can fixed the issue from stale listener.
- https://github.com/prescottprue/react-redux-firebase/issues/838
- …

fix(auth): remove stale profile listener on empty auth state change - @illuminist - #508, #838

---

index.d.ts

For now, loose typings for state make it unsafe to use with typescript. I've added additional type parameter to state, defining `Schema` for database. Consider:
```ts
interface Todo {
description: string;
}
// create schema for the DB
interface DBSchema {
todos: Todo;
}
const rootReducer = combineReducers({
firebase: makeFirebaseReducer<DBSchema>()  // new API for passing type parameter
})
type AppState = ReturnType<typeof rootReducer>;
``` 
Now if we create a selector...
```ts
export const firebaseSelector = (state: AppState) => state.firebase;
export const allItemsSelector = createSelector(
firebaseSelector,
firebase => firebase.data.todos
);
```
we are getting autocompletion!:
... and proper inner type!
Of course, I am open to suggestions, but I literally made the smallest possible …

feat(types): add support for typed db schema

---

examples/complete/simple/package.json

If you attempt to run the simple example, you will get this error:
It's pretty easily solved by the change in this PR.
Not applicable.  I didn't file an issue for this.  Let me know if there needs to be one.

fix(examples): add firebase as a dependency to complete/simple example

---

src/helpers.js
test/mockData.js
test/unit/helpers.spec.js

I understand that populate was designed for RTDB where it doesn't actually have list type for an array, thus when using with firestore list type(array), it outputs an object with index as a key instead of an actual array. So this little change fixes `populate` to be able to handle firestore list and it will output an array instead of plain object.

fix(populate): handle firestore list type in populate

---

index.d.ts

fixed this.
https://github.com/prescottprue/react-redux-firebase/pull/826/files#r386035738

fix(types): switch order of schema type arguments - @macinjoke

---

docs/firestore.md

Adding example for error 'Queries with subcollections must use "storeAs"..' to avoid ongoing misunderstandings.

chore(docs): add example for fixing "subcollection must use storeAs" error - @rusakovic  

---

docs/firestore.md

Minor tweak.  Since this useSelect() returns just one item, change the variable name to make its use clearer.

fix(docs): use correct variable in firestore example

---

docs/firestore.md

Suggested tweak to example code.  The query already limits to fetching one specific document (doc: todoId), so the result set will have just a single entry in the todos array.  I'm not even sure if ordered.todos[todoId] would even work - my brief testing shows that it would yield undefined ?

fix(docs): correct state selector in firestore example - @gregfenton

---

docs/FAQ.md

Fixed gitter-url by adding protocol.
Question to reviewers: should we update all absolute URLs to have https:// as the protocol rather than http:// ?

fix(docs): update protocol of gitter link in FAQ

---

docs/populate.md

I believe the result would not filter down to just "email", or at least the example doesn't seem to indicate how that would occur.
I also removed the "equivalent string notation" as I can't find what that would be for childAlias.  (Is there documentation of the string notation somewhere?  It seems to be embedded into the Object notation/API documentation?)

fix(docs): add missing field to populate example - @gregfenton

---

docs/firestore.md

fix(docs): use correct wording in firestore query docs

---

index.d.ts

Firestore types update
1. Firestore .set allows for options to be passed as well.
2. Added typescript generics support to get/set/update/add/delete

feat(types): generic types for firestore methods

---

index.d.ts

To fix the following:
```sh
node_modules/react-redux-firebase/index.d.ts:1:8 - error TS1259: Module '"/Users/danila/Projects/MyProject/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag
1 import React from 'react'
~~~~~
node_modules/@types/react/index.d.ts:64:1
64 export = React;
~~~~~~~~~~~~~~~
This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```

fix(types): use correct import for react in types

---

docs/queries.md

On the PARSED section of the Queries page there is an incomplete sentence/thought:
>Useful when attempting to parse
I completed it to read:
>Useful when attempting to parse query parameters into the actual value or particular data type ( e.g. null, number, boolean) instead of the string containing the value. 

fix(docs): complete sentence under parsed (#925)

---

docs/queries.md

Corrected mismatching example in Queries doc page, under limitToFirst as highlighted in the issue here: #935

fix(docx): Non-matching example in Queries doc page (#935)

---

docs/api/firestoreConnect.md
docs/api/useFirestoreConnect.md

QUESTION: this page still indicates that "populate is not supported".  Is this still the case for firestore?

fix(docs): cleanup minor typo in useFirestoreConnect.md

---

test/unit/reducer.spec.js

I made tiny change in `test/unit/reducer.spec.js`
I unified to "merges"

chore(tests): fix typo "merge" to "merges" in reducer test file

---

docs/firestore.md

End of page was very confused, formatting-wise.
- made all "Examples" sections consistently indented/formatted
- the *Populate* section now renders correctly

chore(docs): formatting fixes in firestore docs section

---

index.d.ts

- Prefers extending the base interfaces for Firestore/FirebaseExtendedInstance instead of using intersections throughout the types
- Adds `FirebaseDatabaseService` types so that you can achieve:
```ts
...
const firebase = useFirebase();
firebase.database.ServerValue.TIMESTAMP
...
```
- Correct types for FirestoreStatics so you can achieve:
```ts
const firestore = useFirestore();
firestore.FieldValue.serverTimestamp()
```
_Previously, you would've gotten 'serverTimestamp() is a static member of FieldValue'_
- Fixes `useFirestore()` types - previously `withFirestore` would've been close, but `useFirestore` was missing statics.
We've also added inference for plugins, such as performance, analytics, remoteConfig, etc. When a user `import`s those plugins, TS will automatically allow a user to …

feat(types): add database and firestore statics

---

docs/populate.md

Docs do mention populate is supported in firestore.md, however the how-to was missing.
none

feat(docs): add firestore populate docs

---

index.d.ts

We know that if `isLoaded()` helper returns `true` the argument is not `undefined`.
I added an overload to isLoaded function type so that it will narrow type of its argument.
Unfortunately this only works for single argument (we can't have type predicates that reference spread arguments).
Fixes #955

feat(types): add type predicate to isLoaded

---

docs/firestore.md

Explicitly link to redux-firestore API for query options.  There are links to redux-firestore; this context of when to look at the query options is helpful.

chore(docs): link to Query Options in firestore section

---

index.d.ts

`updateProfile` return `void`, but actual type is `Promise` (closes #975)

fix(types): change updateProfile return type

---

docs/auth.md
index.d.ts
src/constants.js
src/utils/auth.js
test/unit/utils/auth.spec.js

Hey there, this PR is for #971. I stumbled across this issue and since I'm working on a project that uses the Apple auth I thought it would have been worth it to add the other providers too.
The main addition in this PR is the provider type for the Credentials. I edited `createAuthProvider` to account for apple.com and yahoo.com and added it to `supportedAuthProviders`.
The unit test has been updated also to reflect the addition I made.
It's not a big one but hopefully it helps. Btw, I started using this package a couple of months ago and I'm loving it so far.
Let me know if there's anything that might need changing. Cheers.
#971

feat(auth): github OAuth provider option in login

---

package-lock.json
package.json
src/firebaseConnect.js
src/firestoreConnect.js

sorry I am not a git pro....I created a branch based on 2.5.0 and then made edits based on that commit.

v2.5.1 remove lifecycle warning of using componentWillMount

---

src/actions/auth.js

fix(auth): dispatch proper error on reset password

---

index.d.ts

See the linked issue: This fixes how Typescript describes the static elements of `firestore` as implemented by Firebase.
#1012
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prescottprue/react-redux-firebase/1013)

fix(types) move static firestore interface to where it's implemented

---

docs/auth.md
index.d.ts
src/actions/auth.js
src/createFirebaseInstance.js
test/unit/actions/auth.spec.js
test/unit/createFirebaseInstance.spec.js
test/utils.js

Add [applyActionCode](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#applyactioncode) to extended firebase instance. I coded it looking at verifyPasswordResetCode, it does nearly the same, so there is not much difference.

feat(auth): add applyActionCode method

---

index.d.ts

This PR fixes a couple minor errors in the type declaration for `react-redux-firebase`. They're all very simple fixes and look like minor typos or missed spots when bulk updating types.
Screenshot of the errors fixed:
https://github.com/prescottprue/react-redux-firebase/issues/997

fix(typescript): fix reloadAuth argument type and duplicate of endBefore

---

index.d.ts

The current typings does not allow you to specify the credential parameter of the credentials in login. This PR changes it to match the implementation.

fix(auth): fix argument type for login with credentials

---

src/actions/auth.js

My configuration is  ```userProfile:  null,  enableClaims: true``` (ref: #1008) and without setup firebase/database.
It throws "firebase.database is not function" error in firebase.logout.

fix(auth): unWatchUserProfile error when database is not setup

---

src/actions/query.js

`src/actions/query.js` hooks the listener for each component. If the same data is used in multiple components on the same page each component will trigger a rerender for the other components as well. The amount of renders due to same data updates seem to follow the equation `2*n^2` where `n` is the number of components using the same data. This increases quite quickly and freezes the app.
Following example demonstrates the issue. The render method for `Avatar` is called 840 times. After the patch the render calls go down to 60.
```jsx
import React from 'react'
import { isLoaded, isEmpty, useFirebaseConnect } from 'react-redux-firebase'
import { useSelector } from 'react-redux'
const Avatar = ({ uid }) => {
useFirebaseConnect(`profiles/${uid}`)
const avatar = useSelector(state => …
```

fix(actions): do not dispatch duplicate events from already hooked listeners

---

docs/api/firestoreConnect.md

The ending parentheses was missing.

fix(docs): added missing ')' to end wrap of connect

---

docs/auth.md

At the Auth page, logout() section, the link to the constants page is broken because an "s" is missing from the constants page link.

fix(docs): broken link caused by typo - #1073

---

src/actions/auth.js
src/createFirebaseInstance.js
src/utils/auth.js
test/unit/createFirebaseInstance.spec.js

feat(auth): support passwordless sign-in

---

src/utils/populate.js

fix(populate): take child param into account when populating

---

docs/FAQ.md

FAQ has an incorrect (dead 404) link to `profileFactory`.

chore(docs): incorrect link (404) to `profileFactory` in FAQ
