src/actions/query.js

"populate" parameter is not working due to this bug.

Update query.js Critical Bug Fix

---

README.md
package.json
src/utils/auth.js
test/unit/utils/auth.spec.js

* External Auth Providers without scopes now handled (Fixes #18)
* Twitter option added to unit tests (confirms handling of providers without scopes)

Version v1.1.3

---

docs/roadmap.md
examples/complete/material/src/containers/Home/Home.js
examples/complete/simple/src/App.js
package.json
src/utils/populate.js
src/utils/query.js

* UID Lists with value `true` now supported (from #23):
```js
{
'absdfTGTdd-kV': true,
'absdfTGTdd-kX': true
}
```
* Handle `equalTo` query with `true` and `false` (fixes #25)
* Roadmap updated

Version v1.1.4

---

docs/api/helpers.md
docs/auth.md
src/helpers.js

* Undefined `populatedDataToJS` children handled
* Docs updated with exposure of `auth()`
* Fixes of small errors in docs (spacing/typos)

Version v1.2.2

---

README.md

Needed for react-auth-wrapper to work properly with react-redux-firebase.

Add predicate for react-auth-wrapper example

---

src/helpers.js

* `populatedDataToJS`: Checks for existence of child objects before checking child parameter   (fixes `param` of `undefined` errors )

Version v1.2.4

---

docs/api/compose.md
docs/api/constants.md
package.json
src/actions/auth.js
src/compose.js
src/constants.js
src/utils/populate.js
src/utils/query.js
test/unit/actions/auth.spec.js
test/unit/utils/actions.spec.js
test/unit/utils/events.spec.js
test/unit/utils/index.spec.js
test/unit/utils/populate.spec.js
test/unit/utils/query.spec.js
test/unit/utils/storage.spec.js

* Single Item Single Child population data loading fixed
* `autoPopulateProfile` config option added for enabling/disabling auto population when using `profileParamsToPopulate` (`true` by default)
* `setProfilePopulateResults` config option added for enabling/disabling setting of profile population results to the data path of redux (`false` by default)
* Docs updated with config options

Version v1.2.5

---

package.json
src/actions/auth.js
src/compose.js
tests/unit/actions/auth.spec.js
tests/unit/compose.spec.js

* Adds `confirmPasswordReset` action
* Adds tests for `confirmPasswordReset` action
* Fixes typo in `test` npm script

confirmPasswordReset action

---

package.json
src/actions/storage.js

The promise from 'uploadFile' now returns an object of the file data is decorated with a `pushKey` property that is the key generated by the call to `firebase.push`.  This change will give the caller the ability to access the urls, name and key for additional processing.
a single `.then` with a spread
Ensure the caller of this function has access to the fileData in the returned promise.
This change is proposed as the caller may need to dispatch additional actions for use with redux/redux-observable that contain the information contained in the fileData.

Return file snapshot on upload

---

examples/complete/simple/src/App.js
examples/complete/simple/src/Home.js
examples/complete/simple/src/TodoItem.js
examples/complete/simple/src/index.js

* Home component added to allow index to be wrapper that includes context (needed for tests to pass)

chore (examples/complete/simple): tests passing

---

docs/recipes/routing.md

The isInitializing selector should be the same regardless of the predicate

fix(docs): fixed authenticatingSelector documentation

---

docs/recipes/routing.md

Add a missing comma to advanced routing recipe

---

examples/snippets/webpack2/index.html
examples/snippets/webpack2/package.json
examples/snippets/webpack2/src/app.js
examples/snippets/webpack2/src/config.js
examples/snippets/webpack2/src/reducer.js
examples/snippets/webpack2/src/store.js
examples/snippets/webpack2/webpack.config.js

Webpack 2 example updated to actually use firebaseConnect instead of just importing it
* [#128](https://github.com/prescottprue/react-redux-firebase/issues/#128)

examples(webpack2): now uses firebaseConnect

---

docs/roadmap.md
examples/snippets/populates/App.js
examples/snippets/populates/README.md
examples/snippets/stateBasedQuery/App.js
examples/snippets/stateBasedQuery/README.md
examples/snippets/stateBasedQuery/Todos.js

* State based query example updated with:
* README now has a step by step walkthrough of what is happening
* Auth now handles loading in a parent component
* Populates README updated with step by step walkthrough of what is happening
* Roadmap updated

snippets(state-based-query): auth loading handled in parent component

---

docs/api/compose.md
docs/api/constants.md
docs/roadmap.md
package.json
src/actions/auth.js
src/constants.js

- Return correct promise from `firebase.auth().signOut()` - #152 
- Typings will included in publish - #142

Version v1.5.0 Beta 2

---

.npmignore
package.json

* Switched to using `.npmignore` instead of `files` and `filesMap` fields in package.json to get typescript typings to be published - #142

Version v1.5.0 Beta 3

---

docs/recipes/README.md
docs/recipes/roles.md

Add recipe for adding roles and access management.
- Will a new version need to be released or is this a docs change?
Just a docs change

feature(docs): add roles recipe to the docs

---

package.json
src/utils/query.js

* Fixes an issue that when attempting to query on Windows in Internet Explorer would cause error with message "isNan is not a method of Number"

Version v1.4.2

---

package.json
src/utils/index.js
src/utils/query.js

* `onAuthStateChange` added to config validation
* deprecation warning added for `config.distpatchOnUnsetListener`

Version v1.4.3

---

examples/complete/simple/src/Home.js

Really minor fix for one of the examples. Didn't know if I should create an issue first since it's such a minor change.

(minor)Fix React declaration in Home component

---

src/createFirebaseInstance.js
src/utils/auth.js
tests/unit/reducer.spec.js
tests/unit/utils/auth.spec.js

* `credential` support added to `login` method - #185 
* signInWithCredential provider & token combo no longer supported due to support
of passing credential - #185 
* Test added to confirm error is thrown for using signInWithCredential
& token
* Logging only called if it exists - #184

feat(login): credential support in login method

---

src/reducer.js

Fixes #219 by using lodash's `set` one level higher in the reducer. 
- [N/A] Docs updated with any changes or examples
- [N/A] Added tests to ensure feature(s) work properly
#219

fix(listeners): deep path listeners not working bug (#219)

---

docs/api/compose.md
examples/complete/material/src/containers/Navbar/Navbar.js
package-lock.json
package.json
src/actions/auth.js
src/firebaseConnect.js
src/reducer.js
tests/unit/actions/storage.spec.js
webpack.config.js
yarn.lock

* Fixes issue with deep listener paths - #219, #221 
* react `v16.0.0-0` added to peer dependencies
* Webpack updated to `v3.4.1`
* `presence` and `sessions` options support passing a function:
```js
{
userProfile: 'users',
// list of online users organize by group parameter
presence: (user) => `presence/${user.group}`,
sessions: (user) => `sessions/${user.group}`
}
```
* `sessions` option can now be set to null to not writing user sessions when using `presence`
* Removed unnecessary constructor from `FirebaseConnect` component
* `combineReducers` is now internal instead of being imported from redux (shrinks bundle size and limits dependencies)
* [Material-UI example](https://github.com/prescottprue/react-redux-firebase/tree/v2.0.0/examples/complete/material) updates (Navbar state uses …

v2.0.0 Beta 4

---

.gitignore
src/actions/query.js

https://github.com/prescottprue/react-redux-firebase/issues/226

Rn sources must be an object fix

---

.eslintignore
.gitignore
bin/api-docs-upload.js
examples/complete/material/src/routes/Home/containers/HomeContainer.js
examples/complete/material/yarn.lock
package.json
src/actions/auth.js
src/actions/query.js
src/helpers.js
src/utils/populate.js

* Fix bug in `updateProfile` method - #210
* Fix population with deep root - #223
* Fix RN sources must be an object error - #228, #231
* Fix an issue using string notation within `profileParamsToPopulate`
* `hoist-non-react-statics` updated
* `npm run docs:upload` added for uploading version specific docs (`npm run docs:publish` still used for publishing main version)
* fixed login method return signature (object including `user`) - #206
* #210
* #223
* #228
* #231

v2.0.0 beta.5

---

.gitignore
README.md
docs/api/compose.md
docs/api/constants.md
docs/api/helpers.md
docs/api/props-firebase.md
docs/recipes/epics.md
docs/recipes/profile.md
docs/recipes/roles.md
docs/recipes/routing.md
docs/storage.md
src/compose.js
src/constants.js
src/helpers.js

Grammar nazi strike with Grammarly 😄 
I'm not fluent in English so let me know if some of my changes should be reverted.
For docs that autogenerated I updated sources and run `docs:build`. Not sure if that was the right thing to do. As far as I understand you'll need to run docs:publish afterward.

Minor grammar fixes in docs, recipes

---

docs/api/reducer.md
docs/auth.md
docs/contributing.md
docs/getting_started.md
package-lock.json
package.json
src/reducer.js
tests/unit/reducer.spec.js
yarn.lock

* feat(reducers): `authError` reducer added to mirror authError state in v1 - #237
* fix(populate): Update to deep path roots do not work with population - #241
* fix(auth docs): Login method docs for authWithCustomToken updated - #245
* #237
* #241
* #245

V2.0.0 beta.6

---

README.md

Just wanted to fix a broken link on the README.

fix broken contributors link

---

docs/firestore.md

Fix a typo, `config` -> `firebaseConfig`

Fix typo in docs/firestore.md

---

src/reducer.js
tests/unit/reducer.spec.js

Only call recursiveUnset for 'data' reducer and add REMOVE tests

---

README.md

Change firebaseStateReducer to firebaseReducer in the README.md example

Change firebaseStateReducer to firebaseReducer in the README.md example

---

.travis.yml
docs/api/firebaseInstance.md
docs/integrations/redux-persist.md
docs/recipes/actions.md
docs/recipes/populate.md
docs/recipes/profile.md
docs/recipes/routing.md
docs/recipes/upload.md
examples/complete/material/.firebaserc
examples/complete/material/package-lock.json
examples/complete/material/src/routes/Home/components/NewTodoPanel/NewTodoPanel.js
examples/complete/material/src/routes/Home/components/TodosList/TodosList.scss
examples/complete/material/src/routes/Home/containers/HomeContainer.js
examples/complete/material/src/routes/Home/containers/HomeContainer.scss
examples/complete/material/src/routes/Projects/containers/ProjectsContainer.js
examples/complete/material/src/store/createStore.js
package-lock.json
package.json
src/actions/auth.js
src/constants.js
src/createFirebaseInstance.js
src/firebaseConnect.js
src/helpers.js
src/reducer.js
src/utils/actions.js
src/utils/auth.js
src/utils/events.js
src/utils/query.js

* feat(auth): `UNLOAD_PROFILE` is dispatched when `login` action creator is called  - #301
* feat(auth): `signInWithPhoneNumber` action creator added - #319
* fix(firebaseConnect): function passed receives consistent arguments regardless of lifecycle - #320
* fix(query): `queryId` now includes `storeAs` to fix issue with listeners - #294
* fix(populate): ordered (array data) correctly populating - #239 - thanks @0x80 
* fix(reducer): property removed from profile is removed from state - thanks @fej-snikduj 
* fix(docs): inconsistencies in redux-auth-wrapper example - #325
* #239
* #294
* #301 
* #319
* #320
* #325

v2.0.0 beta.15

---

docs/queries.md

fix(docs): Add missing coma in the queries doc

---

docs/recipes/actions.md
docs/recipes/profile.md
package-lock.json
package.json
tests/unit/firestoreConnect.spec.js

* feat(firestoreConnect): support `componentWillReceiveProps` in `firestoreConnect` (props/query params change) - #354 - @danleavitt0
* feat(docs): actions docs updated with `recompose` examples (for more simple functional components)
* fix(docs): profile docs updated with new wording (clarifies usage)
* fix(build): `codecov` npm script updated to fix warning
* #354

v2.0.0-beta.19

---

docs/recipes/thunks.md

Grammar nazi

---

README.md

On line 66, it says 
"add reduxReduxFirebase enhancer.
I believe this is just a typo.
I switched it over to reactReduxFirebase
- [ x] Docs updated with any changes or examples if applicable

Just a small typo.

---

src/reducers.js

Reload auth action was missing a reducer to update the redux state with new auth information.
#273

feat(auth): Reload auth reducer missing

---

src/reducers.js

* feat(profileReducer): PROFILE_UPDATE_SUCCESS action updates profile state - #395 - @serhiipalash 
* #395

Update profile reducer each time “PROFILE_UPDATE_SUCCESS” action goes

---

src/actions/auth.js

Here is the full explanation to the issue: #401 

fix(login): login-logout-login flow always correctly updates firebase.profile - #401 - @evgeni-tsn

---

src/actions/auth.js

https://github.com/prescottprue/react-redux-firebase/issues/391
this fixes #391 
If the user has provided a profileFactory, we use the generated profile from it.
If the user didn't provide a profileFactory we go over the default code for generating a profile. Firestore delivers the creationTime and lastSignInTime in the metadata property. So doing userDataObject.createdAt was undefined and the stringToDate function was throwing an error

fix(profile): profileFactory support for firestore

---

src/helpers.js
src/utils/populate.js

Hi. creating PR for issue described below.
I tried to solve it using callback as you wrote,but in vain.
Added on property check if true. It doesn't brake existing methods.
Tested on my app. Works fine!!
https://github.com/prescottprue/react-redux-firebase/issues/349

populate method: use populateBykey = true to find items by key

---

docs/recipes/actions.md

Fix `actions.md` link to thunk section

update docs link for thunk integration

---

docs/populate.md

Fixed a 404 link for populates docs.

Fix(docs): Fixed a 404 link for populates

---

README.md

Fix(docs): Add redux-firestore import to README.md example

---

docs/recipes/auth.md

Add missing import to the wait for auth example code.

Add missing import: getFirebase

---

examples/complete/firestore/README.md
examples/complete/simple/README.md

Update a broken link :)
- [ x] All tests passing
- [ x] Docs updated with any changes or examples if applicable
- [ x] Added tests to ensure new feature(s) work properly

Update create-react-app guide links

---

docs/v2-migration-guide.md

Fix typo - Pass in the correct fbconfig parameter

---

docs/integrations/redux-saga.md

Update redux-saga doc to pass in firebase instance (v2)

---

.travis.yml

Set install setup in attempt to prevent issue with npm ci.

---

.eslintrc
package-lock.json
package.json
src/actions/auth.js
src/index.js
src/utils/storage.js
test/.eslintrc
test/setup.js
test/unit/actions/auth.spec.js
test/unit/actions/storage.spec.js
test/utils.js

* fix(storage): uploadFile gets downloadURL before writing metadata - #487, #488
* fix(storage): add unit tests for `fileMetadataFactory` (config level) and `metadataFactory` (option for uploadFile) to confirm downloadURL is available before writing metadata - #487, #488
* fix(storage): fix downloadURL error in file upload metadata - @jpierce42
* fix(auth): `LOGOUT` action dispatch only include preserve parameter if provided in settings (not when undefined)
* #487 
* #488

v2.2.0-alpha.2

---

docs/api/connect.md

Fixes property name in the example.

fix(docs): fix property name

---

package-lock.json
package.json
src/utils/storage.js
test/unit/actions/storage.spec.js
test/utils.js

* fix(storage): prevent `undefined` (within metadata) from being written to database which causes an error for RTDB
* fix(storage): return metadata push key from upload promise - #547
* #547

v2.2.0-alpha.3

---

.babelrc
examples/complete/simple/src/Home.js
examples/complete/simple/src/TodoItem.js
package-lock.json
package.json
src/ReactReduxFirebaseProvider.js
src/ReduxFirestoreProvider.js
src/firebaseConnect.js
src/firestoreConnect.js
src/utils/index.js
src/withFirebase.js
src/withFirestore.js

* fix(firestoreConnect): remove remaining usage of old context pattern - #594
* fix(HOCs): add displayName to `firebaseConnect` and `firestoreConnect`
* #594

v3.0.0-alpha.3

---

.babelrc
docs/api/firebaseInstance.md
docs/api/firestoreConnect.md
docs/api/withFirebase.md
docs/api/withFirestore.md
index.d.ts
package-lock.json
package.json
src/ReactReduxFirebaseProvider.js
src/ReduxFirestoreProvider.js
src/actions/storage.js
src/createFirebaseInstance.js
src/utils/actions.js

* fix(typings): add context providers to typings - #564
* fix(storage): support only firestore when calling upload and writing to db - @dirathea
* fix(core): add auth initialization to providers to match v2 store enhancer - #388
* #388
* #564

v3.0.0-alpha.4

---

README.md
package-lock.json
package.json
src/ReactReduxFirebaseProvider.js

* fix(core): fix misspelled `defaultProp` on `ReactReduxFirebaseProvider` - #564

v3.0.0 alpha.5

---

docs/recipes/auth.md
package.json
src/createFirebaseInstance.js
src/firestoreConnect.js

* feat(auth): exposing handleRedirectResult for react-firebaseui - #608 - @dirathea
* #608

v3.0.0-alpha.6

---

index.d.ts

fix(typings): update more types including orderBy options

---

package-lock.json
package.json
src/firebaseConnect.js
test/unit/firebaseConnect.spec.js
test/utils.js

* fix(firebaseConnect): add back firebase + dispatch props - #582, #613
* fix(typings): update more types including orderBy options
* fix(tests): add case to firebaseConnect to confirm firebase and dispatch props
* #582 
* #613

v3.0.0-alpha.9

---

index.d.ts

fix(typings): updated TypeScript typings including use of Dictionary - @rscotten

---

index.d.ts
package-lock.json
package.json
src/createFirebaseInstance.js

* fix(createFirebaseInstance): merge internals on instance recreation - #174 - @gotdibbs
* fix(typings): updated TypeScript typings including use of Dictionary - @rscotten
* #174

v3.0.0-alpha.10

---

docs/firestore.md

From comment here: https://github.com/prescottprue/react-redux-firebase/issues/344#issuecomment-367854912
#344

Fix docs: Get specific todo with firestoreConnect

---

docs/firestore.md

Fixes a tiny typo :)

---

index.d.ts

Upgrade typescript definitions

---

index.d.ts
package-lock.json
package.json

* fix(types): improve query param types and add type for options object - @rscotten

v3.0.0 alpha.11

---

docs/getting_started.md

fix(docs): fix broken link to config options

---

docs/firestore.md

fix(docs): fix typo in firestore query docs

---

package-lock.json
package.json
src/firestoreConnect.js

* fix(firestoreConnect): pass correct value for `firebase` prop - #758
* #758

v3.0.0-beta.2

---

docs/recipes/profile.md
package-lock.json
src/actions/auth.js

Adding "firebase" parameter to profileFactory callback, allowing access to the firebase & firestore object before setting the users profile & updating docs.

feat(profileFactory): adding "firebase" parameter to profileFactory callback

---

docs/api/firebaseInstance.md
docs/auth.md
index.d.ts
src/createFirebaseInstance.js
test/unit/createFirebaseInstance.spec.js

#803 This PR fix the problem mentioned in this issue
#803

Fix documentation about resetPassword

---

examples/complete/firestore/src/Todos.test.js

This commit adds test cases to firestore example to let users know how to test the components which are using RRF hooks. 
Resolves: #788 

test(example): add test cases to simple firestore example

---

docs/recipes/auth.md

Adds missing div tag to Firebase UI React example

Adds missing div tag to Firebase UI React example

---

docs/recipes/profile.md

Just fixing a wrong import on update profile example, the example implements hooks API but imports the HOC API.

Fix import on update profile example

---

docs/auth.md
src/actions/auth.js
src/createFirebaseInstance.js
src/reducers.js
src/utils/auth.js

Call to reauthenticate method can be needed when user need to update sensible datas, like the current email used for connection.

feat(auth): add reauthenticate method from firebase

---

docs/recipes/roles.md

Fixed outdated examples for redux-auth-wrapper in roles recipe. Fixes issue #860 .

fix(docs): update roles recipe to reflect redux-auth-wrapper v2 changes - @markoelez 

---

index.d.ts

2 changes
- Add missing onAuthStateChanged for config object
- Relax typing for UserProfile to be generic object

fix(types): add onAuthStateChanged type to config and make UserProfile generic

---

docs/auth.md
src/constants.js
src/utils/auth.js
test/unit/utils/auth.spec.js

Add support for Microsoft OAuthProvider using Firebase.

feat(auth): add support for microsoft oauthprovider - @lucasharada

---

docs/firestore.md

fix(docs): fix grammatical errors in redux-firestore explanation - @gregfenton

---

docs/v3-migration-guide.md

fix(docs): update link to v3 migration guide - @gregfenton

---

docs/queries.md

update the link
https://firebase.google.com/docs/reference/js/firebase.database.Query#order-bychild

fix(docs): update link of orderByChild in queries docs - @rusakovic 

---

.eslintignore
index.d.ts

fix(types): add type for profileFactory (#917)

---

docs/recipes/roles.md

fix(docs): clear up description of role in roles recipes

---

src/utils/auth.js

fix(docs): correct wording of updateProfileOnRTDB param description

---

docs/integrations/react-native.md

Link to the specific historic URL of the github repo (the file has since been deleted).
* fixes https://github.com/prescottprue/react-redux-firebase/issues/978

fix(docs): fix xcode config image in react-native integration section

---

src/helpers.js

Added support for storeAs when populating child object from redux

feat(populate): added support for storeAs when populating child from redux

---

index.d.ts

fix(types): add arguments to types for onAuthStateChanged

---

docs/auth.md
examples/complete/firestore/yarn.lock
examples/complete/react-native-firebase/yarn.lock
examples/complete/react-native/yarn.lock
examples/complete/simple/yarn.lock
examples/complete/typescript/yarn.lock
package-lock.json
package.json

- Upgrades npm audit level critical packages lodash and firebase-server
- Merges all dependabot branches that would apply cleanly
First PR for #1143

chore(deps): update critical lodash and firebase-server and merge dependabot PRs - @sesam

---

docs/queries.md

fix(docs): correct the example of "Non-number values" queryParams
